// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: proto/v1/notificator.proto

package protov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NotificatorService_Notify_FullMethodName = "/proto.v1.NotificatorService/Notify"
)

// NotificatorServiceClient is the client API for NotificatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificatorServiceClient interface {
	Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error)
}

type notificatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificatorServiceClient(cc grpc.ClientConnInterface) NotificatorServiceClient {
	return &notificatorServiceClient{cc}
}

func (c *notificatorServiceClient) Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error) {
	out := new(NotifyResponse)
	err := c.cc.Invoke(ctx, NotificatorService_Notify_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificatorServiceServer is the server API for NotificatorService service.
// All implementations should embed UnimplementedNotificatorServiceServer
// for forward compatibility
type NotificatorServiceServer interface {
	Notify(context.Context, *NotifyRequest) (*NotifyResponse, error)
}

// UnimplementedNotificatorServiceServer should be embedded to have forward compatible implementations.
type UnimplementedNotificatorServiceServer struct {
}

func (UnimplementedNotificatorServiceServer) Notify(context.Context, *NotifyRequest) (*NotifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Notify not implemented")
}

// UnsafeNotificatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificatorServiceServer will
// result in compilation errors.
type UnsafeNotificatorServiceServer interface {
	mustEmbedUnimplementedNotificatorServiceServer()
}

func RegisterNotificatorServiceServer(s grpc.ServiceRegistrar, srv NotificatorServiceServer) {
	s.RegisterService(&NotificatorService_ServiceDesc, srv)
}

func _NotificatorService_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificatorServiceServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificatorService_Notify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificatorServiceServer).Notify(ctx, req.(*NotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificatorService_ServiceDesc is the grpc.ServiceDesc for NotificatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.v1.NotificatorService",
	HandlerType: (*NotificatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Notify",
			Handler:    _NotificatorService_Notify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/notificator.proto",
}
