"use strict";
// @generated by protoc-gen-es v1.4.1 with parameter "target=ts"
// @generated from file proto/v1/notificator.proto (package proto.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck
Object.defineProperty(exports, "__esModule", { value: true });
exports.NotifyResponse = exports.NotifyRequest = void 0;
const protobuf_1 = require("@bufbuild/protobuf");
/**
 * @generated from message proto.v1.NotifyRequest
 */
class NotifyRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        /**
         * @generated from field: string message = 1;
         */
        this.message = "";
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new NotifyRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new NotifyRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new NotifyRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(NotifyRequest, a, b);
    }
}
exports.NotifyRequest = NotifyRequest;
NotifyRequest.runtime = protobuf_1.proto3;
NotifyRequest.typeName = "proto.v1.NotifyRequest";
NotifyRequest.fields = protobuf_1.proto3.util.newFieldList(() => [
    { no: 1, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
]);
/**
 * @generated from message proto.v1.NotifyResponse
 */
class NotifyResponse extends protobuf_1.Message {
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static fromBinary(bytes, options) {
        return new NotifyResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new NotifyResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new NotifyResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(NotifyResponse, a, b);
    }
}
exports.NotifyResponse = NotifyResponse;
NotifyResponse.runtime = protobuf_1.proto3;
NotifyResponse.typeName = "proto.v1.NotifyResponse";
NotifyResponse.fields = protobuf_1.proto3.util.newFieldList(() => []);
