// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts"
// @generated from file proto/v1/notificator.proto (package proto.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { NotifyRequest, NotifyResponse } from "./notificator_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service proto.v1.NotificatorService
 */
export const NotificatorService = {
  typeName: "proto.v1.NotificatorService",
  methods: {
    /**
     * @generated from rpc proto.v1.NotificatorService.Notify
     */
    notify: {
      name: "Notify",
      I: NotifyRequest,
      O: NotifyResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

